### ISSUE TITLE
Soundex or Double Metaphone predicate

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe#324]

**Comment by fgregg** [comment]
Looks like @al45tair already did it? @al45tair, any plans to push your unicode compatible version to pypi?

**Comment by al45tair** [comment]
I hadn't particularly planned to, but as it's useful to you I've just done so (I named my version "metafone" so as not to conflict with the official version).

**Comment by al45tair** [comment]
FWIW, the version you’ve uploaded (under the name "unicode-metaphone" is missing a couple of minor fixes). I had intended just to use the code privately as part of my vat package, as I can't legitimately claim credit for most of the changes — they’re just from other github repos where people had already fixed the problems I was seeing (and their changes seemed reasonable).

**Comment by fgregg** [comment]
Great! I'll switch to your version,

On Monday, February 16, 2015, Alastair Houghton <notifications@github.com>
wrote:

> FWIW, the version you’ve uploaded (under the name "unicode-metaphone" is
> missing a couple of minor fixes). I had intended just to use the code
> privately as part of my vat package, as I can't legitimately claim credit
> for most of the changes — they’re just from other github repos where people
> had already fixed the problems I was seeing (and their changes seemed
> reasonable).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/324#issuecomment-74485828>.
>


-- 
773.888.2718

**Comment by al45tair** [comment]
Probably worth saying that I’ve filed a pull request with the upstream repository to take the changes. It'd be nice if there was just the one metaphone package :-D

**Comment by fgregg** [comment]
Totally agree! I was going to delete the pypi repo I just made.

**Comment by fgregg** [comment]
Thanks so much. BTW, what's your vat project?

**Comment by al45tair** [comment]
This:
https://bitbucket.org/al45tair/vat

I’d like to see it gain functions for other (non-UK) VAT purposes as well as various other things, and I’m presently trying to get the EU to publish its VAT data in a more sensible format (see https://bitbucket.org/al45tair/vat-info if you’re interested in that).

(I’m part of a working group here in the UK, consisting of some representatives from small business and also some people from HMRC, which is responsible for talking through some of the problems with the 1st January Place of Supply changes and the Mini One Stop Shop system, so I have some useful contacts for these kinds of things and hopefully will be able to make a bit of headway.)

**Comment by fgregg** [comment]
Very cool! Sounds like the kind of project that @theodi or @mySociety would be interested in? Do you know @steiny, or any of those folks?

**Comment by al45tair** [comment]
Can’t say I do, but if @theodi, @mySociety, @steiny or indeed anyone else is interested I’m definitely keen to hear their thoughts. I’m also keen to attract contributions from people in other countries for the vat package.
