### ISSUE TITLE
Canonicalize chokes on large groups of records

### ISSUE THREAD

**Issue by evz** [datamade/dedupe#333]
Calling [``canonicalize``](https://github.com/datamade/dedupe/blob/master/dedupe/convenience.py#L179) with thousands of records seems to cause it to hang for quite a while. I called it with a group of ~16,000 records and killed it after waiting for about 40 minutes. Let's see if we can do something about this.

**Comment by webmaven** [comment]
:+1:

**Comment by fgregg** [comment]
Moved to https://github.com/datamade/canonicalize/issues/3
