### ISSUE TITLE
frozendict hashes vary for equal values

### ISSUE THREAD

**Issue by shahin** [datamade/dedupe#339]
Hey, thanks for such a cleanly-designed package.

I am seeing an issue w/ the frozen dictionary implementation. Equivalent frozen dictionaries have different hash values:

```
In [2]: a = {'smtp': 21, 'dict': 2628 }

In [3]: b = {'dict': 2628, 'smtp': 21 }

In [4]: hash(frozendict(tuple(a.items())))
Out[4]: -8110228070231110462

In [5]: hash(frozendict(tuple(b.items())))
Out[5]: -4054501204675263584

In [6]: a == b
Out[6]: True
```

The equality function for dictionaries is not a function of order. The hash for frozendict is a function of the order, though (via tuple(), via items()):
```
def __hash__(self):
    try:
        return self._cached_hash
    except AttributeError:
        h = self._cached_hash = hash(tuple(self._d.items()))
    return h
```
I think we should remove all ordering information from the underlying dictionary before hashing its contents, which might mean either:

1. hash(tuple(sort(self._d.items()))), or
2. hash(frozenset(self._d.items())), or
3. other

I'll speculate that (2) might be better performance-wise.

Would you agree that we'd like hash values to be the same in this case? If so, let me know if you'd like a pull request. Thanks again!

**Comment by fgregg** [comment]
Yes, you are right. Please send me a PR, and the frozenset choice looks
good.
