### ISSUE TITLE
commands out of sync

### ISSUE THREAD

**Issue by wcatino** [datamade/dedupe#341]
In my custom code (which is very similar to the mysql example), I got an error while mysql was executing the query
"SELECT id, name, year, "
              "block_id, smaller_ids "
              "FROM smaller_coverage "
              "INNER JOIN " + dataTableName + " "
              "USING (id) "
              "ORDER BY (block_id)"
Here is the traceback:
Traceback (most recent call last):
  File "dedupeAuthor.py", line 477, in <module>
    clustered_dupes = Cluster(c0)
  File "dedupeAuthor.py", line 396, in Cluster
    "INNER JOIN " + dataTableName + " "
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
KeyboardInterrupt
Exception _mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now") in <bound method SSDictCursor.__del__ of <MySQLdb.cursors.SSDictCursor object at 0x3564b90>> ignored

**Comment by wcatino** [comment]
Here is the exact query text:

SELECT id, name, year, block_id, smaller_ids FROM smaller_coverage INNER JOIN dedupeAuthors USING (id) ORDER BY (block_id)

**Comment by wcatino** [comment]
The whole process worked when I limited the data to the first 100 records.
This crash happened when I expanded the limit to 1000 records.
I am retrying.
If any of my subsequent attempts succeed, I will indicate that in another comment.

**Comment by fgregg** [comment]
When you are using the server side cursors, you must *completely* exhaust
one query before you go onto the next query. If you don't you get this
error message.  You can do that with `cur.fetchall()` or similar before
moving to the next query.

**Comment by wcatino** [comment]
That fixed it.  I had a bug - this helped me find it.  Thanks!
