### ISSUE TITLE
Can the algorithms used by dedupe also be used to find unique keys in a dataset?

### ISSUE THREAD

**Issue by jpmckinney** [datamade/dedupe#346]
https://github.com/tlevine/special_snowflake does this but consumes huge amounts of memory and is slow.

**Comment by fgregg** [comment]
Not really, at least not for the definition of unique key that @tlevine is using. Since python ships with sqlite, that code could and should just use sqlite's `DISTINCT` operator.

**Comment by jpmckinney** [comment]
That project tries different combinations of columns until it finds a combination for which all rows have unique values. So, running `DISTINCT` just helps collect the number of rows with distinct values; it depends on how much time SQLite's fast code saves compared to the time it takes to load a big CSV into SQLite. Anyway, I wrote a Ruby version that has a few important optimizations, e.g. if you find a non-distinct row, you can fail right away - no need to keep reading the table! (which SQLite would do and which special_snowflake does).

**Comment by jpmckinney** [comment]
FYI, I added a fast Ruby implementation to https://github.com/jpmckinney/lycopodium#readme
