### ISSUE TITLE
Gazetteer Class

### ISSUE THREAD

**Issue by sjmori** [datamade/dedupe#351]
Hi

I am new to using this library (which is great!) and have tried a couple of the examples which I've managed to work out. 
However I tried to use the Gazeteer class but I am having difficulty reading the results of the Match operation.

I called the Match operation as follows...

linker.index(data_2)
linked_records = linker.match(data_1,0.5,1)

and I tried something similar to the Record Linkage example...

for cluster_id, (cluster, score) in enumerate(linked_records):
    for record_id in cluster:
        cluster_membership[record_id] = (cluster_id, score)

but I get the error message

ValueError: need more than 1 value to unpack

and the contents of the array look like this...

((array([    31, 136944]), 0.9855662),) 

However in the Record Linkage example it looked like this

(array([   642, 105163]), 0.99761122)

How do I read the results and what is the difference between the two? Or is this an actual issue?

thanks
Steve

**Comment by fgregg** [comment]
Unlike the record link method, The gazetteer class can return more than one possible match for a 'search' record. By default it only returns one, but, even in this case, we return a list of possible matches.

**Comment by sjmori** [comment]
Ok understand, many thanks
