### ISSUE TITLE
writeTraining crashes on Decimal data

### ISSUE THREAD

**Issue by shahin** [datamade/dedupe#353]
Python 2.7's json module doesn't support ```Decimal``` serialization. This causes a crash in ```serializer._to_json```, making it difficult to save training data that contains ```Decimal``` fields.

simplejson does support ```Decimal``` [since 2.1.0](https://github.com/simplejson/simplejson/blob/master/CHANGES.txt#L328). But dedupe imports simplejson only in case of a missing json module (Python 2.5?).

Would you consider a patch to import simplejson by default in backport.py, either making it a dependency or falling back to the built-in json where simplejson is unavailable?

**Comment by fgregg** [comment]
Why do you need Decimal serialization?

**Comment by shahin** [comment]
Lots of DB API adapters return arbitrary precision numbers as Decimal, and we store lat/long with arbitrary precision in Postgres (exact equality comparisons are useful for us). So the training data is Decimal when passed to writeTraining for serialization.

**Comment by fgregg** [comment]
ah, okay.
