### ISSUE TITLE
If I get ahead of the human review queue it will look like I'm done

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe#363]
![screenshot from 2015-02-25 22 21 05](https://cloud.githubusercontent.com/assets/536941/6386324/a7e098a4-bd3c-11e4-8fe2-d753e688df76.png)

but then I click Next Match

![screenshot from 2015-02-25 22 21 19](https://cloud.githubusercontent.com/assets/536941/6386327/b1a1e32a-bd3c-11e4-84a6-e5f13597a7af.png)

**Comment by evz** [comment]
Heh, wrong repo. Anyways, did it seem like you were going really fast? I mean, the fix for this might just be to build up a bigger review queue. Right now I'm loading 10. I could easily make it 20.

**Comment by fgregg** [comment]
I was really reviewing. Let's do 20.
