### ISSUE TITLE
IPython notebook can't import dedupe.sampling

### ISSUE THREAD

**Issue by mkemka** [datamade/dedupe#371]
I receive this error in IPython notebook when I attempt to import the module dedupe.sampling:

I can import via IPython and python in the command line and have also tried adding the module folder to the path in the IPython notebook session
'''
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-9352e42e2791> in <module>()
----> 1 import dedupe.sampling
      2 import sys
      3 sys.path.append('/home/ubuntu/src/dedupe')

/home/ubuntu/anaconda/lib/python2.7/site-packages/dedupe/__init__.py in <module>()
      9            ]
     10 
---> 11 from api import StaticDedupe, Dedupe
     12 from api import StaticRecordLink, RecordLink
     13 from api import StaticGazetteer, Gazetteer

/home/ubuntu/anaconda/lib/python2.7/site-packages/dedupe/api.py in <module>()
     21 
     22 import dedupe
---> 23 import dedupe.sampling as sampling
     24 import dedupe.core as core
     25 import dedupe.training as training

AttributeError: 'module' object has no attribute 'sampling'
'''

**Comment by cathydeng** [comment]
hey @mkemka - I tried to reproduce your error in ipython notebook, and didn't have any issue importing dedupe.sampling. perhaps this is a version problem? do you want to use the following code to list what packages you have installed?

```
import pip
sorted(["%s==%s" % (i.key, i.version) for i in pip.get_installed_distributions()])
```

**Comment by fgregg** [comment]
@mkemka couldn't reproduce. Feel free to reopen if you can give us some more feedback.

**Comment by brandomr** [comment]
I had the same issue as @mkemka when I tried to import dedupe within an open workbook where I had already imported numpy.

I opened a new iPython Notebook and copied the imports from [http://datamade.github.io/dedupe-examples/docs/csv_example.html] (the CSV dedupe example) and that worked just fine. I then restarted the kernel on my other notebook and tried the import once more and everything worked fine.

**Comment by fgregg** [comment]
Weird.

**Comment by titipata** [comment]
I had the same error as @mkemka  and then I solved the same problem as @brandomr solved by restarting the kernel on IPython notebook

**Comment by fgregg** [comment]
This sounds more and more like an issue with ipython.

**Comment by fgregg** [comment]
@mkemka, @brandomr, @titipata, could you help us figure out what's going on in this [ipython issue](https://github.com/ipython/ipython/issues/8446)

**Comment by titipata** [comment]
Thanks @fgregg for pointing, I already add comments on the issue. Hope it helps.
