### ISSUE TITLE
Error while configuring openblas for Mac OSX

### ISSUE THREAD

**Issue by asharma567** [datamade/dedupe#376]
Same error as the line at the bottom...
https://readthedocs.org/builds/dedupe/2316678/
x86_64-linux-gnu-gcc: error: src/cpredicates.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

**Comment by fgregg** [comment]
Are you building from source, or installing from pypi?

**Comment by asharma567** [comment]
As instructed in he docs for Mac osx.. Python setup.py install

**Comment by fgregg** [comment]
Which install instructions are you speaking of?

If you are installing from source, which it sounds like you are doing. You
need to build the cpredicates.c from source from the cython files:

https://github.com/datamade/dedupe#developers

**Comment by asharma567** [comment]
What's the difference if I just install via pip?

**Comment by asharma567** [comment]
I also continue to get this error after hand-labeling...

*INFO:dedupe.blocking:1240000, 1417.4469502 seconds*

*Killed: 9*


Would you know how to fix?
ᐧ

On Sun, Apr 12, 2015 at 7:12 PM, Ajay Sharma <asharma567567@gmail.com>
wrote:

> What's the difference if I just install via pip?
> On Apr 12, 2015 7:01 PM, "Forest Gregg" <notifications@github.com> wrote:
>
>> Which install instructions are you speaking of?
>>
>> If you are installing from source, which it sounds like you are doing. You
>> need to build the cpredicates.c from source from the cython files:
>>
>> https://github.com/datamade/dedupe#developers
>>
>> On Sun, Apr 12, 2015 at 8:50 PM Ajay Sharma <notifications@github.com>
>> wrote:
>>
>> > As instructed in he docs for Mac osx.. Python setup.py install
>> > On Apr 12, 2015 6:33 PM, "Forest Gregg" <notifications@github.com>
>> wrote:
>> >
>> > > Are you building from source, or installing from pypi?
>> > > On Sun, Apr 12, 2015 at 7:58 PM Ajay Sharma <notifications@github.com
>> >
>> > > wrote:
>> > >
>> > > > Same error as the line at the bottom...
>> > > > https://readthedocs.org/builds/dedupe/2316678/
>> > > > x86_64-linux-gnu-gcc: error: src/cpredicates.c: No such file or
>> > directory
>> > > > x86_64-linux-gnu-gcc: fatal error: no input files
>> > > > compilation terminated.
>> > > > error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <https://github.com/datamade/dedupe/issues/376>.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/datamade/dedupe/issues/376#issuecomment-92161652
>> >.
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/datamade/dedupe/issues/376#issuecomment-92167526>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/datamade/dedupe/issues/376#issuecomment-92170173>.
>>
>


-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by asharma567** [comment]
failed the nose test

*Traceback (most recent call last):*

*  File
"/Users/asharma.tmp/anaconda/lib/python2.7/multiprocessing/process.py",
line 258, in _bootstrap*

*    self.run()*

*  File
"/Users/asharma.tmp/anaconda/lib/python2.7/multiprocessing/process.py",
line 114, in run*

*    self._target(*self._args, **self._kwargs)*

*  File
"/private/var/folders/_g/qgykzmqx35724p5grp9mjssw3645hw/T/pip_build_asharma.tmp/dedupe/dedupe/core.py",
line 188, in __call__*

*    self.fieldDistance(record_pairs)*

*  File
"/private/var/folders/_g/qgykzmqx35724p5grp9mjssw3645hw/T/pip_build_asharma.tmp/dedupe/dedupe/core.py",
line 213, in fieldDistance*

*    filtered_pairs = scored_pairs[scores > self.threshold]*

*  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/numpy/core/records.py",
line 481, in __getitem__*

*    return obj.view(dtype=(self.dtype.type, obj.dtype.descr))*

*  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/numpy/core/records.py",
line 540, in view*

*    return ndarray.view(self, dtype)*

*  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/numpy/core/records.py",
line 457, in __setattr__*

*    raise exctype(value)*

*TypeError: Cannot change data-type for object array.*
ᐧ

On Sun, Apr 12, 2015 at 7:15 PM, Ajay Sharma <asharma567567@gmail.com>
wrote:

> I also continue to get this error after hand-labeling...
>
> *INFO:dedupe.blocking:1240000, 1417.4469502 <1417.4469502> seconds*
>
> *Killed: 9*
>
>
> Would you know how to fix?
> ᐧ
>
> On Sun, Apr 12, 2015 at 7:12 PM, Ajay Sharma <asharma567567@gmail.com>
> wrote:
>
>> What's the difference if I just install via pip?
>> On Apr 12, 2015 7:01 PM, "Forest Gregg" <notifications@github.com> wrote:
>>
>>> Which install instructions are you speaking of?
>>>
>>> If you are installing from source, which it sounds like you are doing.
>>> You
>>> need to build the cpredicates.c from source from the cython files:
>>>
>>> https://github.com/datamade/dedupe#developers
>>>
>>> On Sun, Apr 12, 2015 at 8:50 PM Ajay Sharma <notifications@github.com>
>>> wrote:
>>>
>>> > As instructed in he docs for Mac osx.. Python setup.py install
>>> > On Apr 12, 2015 6:33 PM, "Forest Gregg" <notifications@github.com>
>>> wrote:
>>> >
>>> > > Are you building from source, or installing from pypi?
>>> > > On Sun, Apr 12, 2015 at 7:58 PM Ajay Sharma <
>>> notifications@github.com>
>>> > > wrote:
>>> > >
>>> > > > Same error as the line at the bottom...
>>> > > > https://readthedocs.org/builds/dedupe/2316678/
>>> > > > x86_64-linux-gnu-gcc: error: src/cpredicates.c: No such file or
>>> > directory
>>> > > > x86_64-linux-gnu-gcc: fatal error: no input files
>>> > > > compilation terminated.
>>> > > > error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
>>> > > >
>>> > > > —
>>> > > > Reply to this email directly or view it on GitHub
>>> > > > <https://github.com/datamade/dedupe/issues/376>.
>>> > > >
>>> > >
>>> > > —
>>> > > Reply to this email directly or view it on GitHub
>>> > > <https://github.com/datamade/dedupe/issues/376#issuecomment-92161652
>>> >.
>>> > >
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <https://github.com/datamade/dedupe/issues/376#issuecomment-92167526>.
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/datamade/dedupe/issues/376#issuecomment-92170173>.
>>>
>>
>
>
> --
> Github <https://github.com/asharma567/> | LinkedIn
> <http://www.linkedin.com/in/mrasharma/>
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by fgregg** [comment]
I can't read the traceback in your last message.

The difference between pip and installing from source is that the pypi packages includes the c fies. 

the "Kill 9" error seems like something to do with multiprocessing on mac. Can't advise without more info.

**Comment by asharma567** [comment]
When the datasets are smaller it works fine...
ᐧ

On Sun, Apr 12, 2015 at 7:30 PM, Forest Gregg <notifications@github.com>
wrote:

> I can't read the traceback in your last message.
>
> The difference between pip and installing from source is that the pypi
> packages includes the c fies.
>
> the "Kill 9" error seems like something to do with multiprocessing on mac.
> Can't advise without more info.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/376#issuecomment-92174653>.
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by asharma567** [comment]
looking at 2.2 million records
ᐧ

On Sun, Apr 12, 2015 at 7:34 PM, Ajay Sharma <asharma567567@gmail.com>
wrote:

> When the datasets are smaller it works fine...
> ᐧ
>
> On Sun, Apr 12, 2015 at 7:30 PM, Forest Gregg <notifications@github.com>
> wrote:
>
>> I can't read the traceback in your last message.
>>
>> The difference between pip and installing from source is that the pypi
>> packages includes the c fies.
>>
>> the "Kill 9" error seems like something to do with multiprocessing on
>> mac. Can't advise without more info.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/datamade/dedupe/issues/376#issuecomment-92174653>.
>>
>
>
>
> --
> Github <https://github.com/asharma567/> | LinkedIn
> <http://www.linkedin.com/in/mrasharma/>
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by fgregg** [comment]
Oh.. there is probably an out of memory error somewhere. Are you blocking in memory? Or to disk like in the myql_example?

**Comment by asharma567** [comment]
cat input_dedupe_large.csv | csvdedupe --field_names contact_id
FirstName_nicks LastName Email Address1 PhoneMobile > output_test_lrg.csv
......128 mb file
ᐧ

On Sun, Apr 12, 2015 at 7:37 PM, Forest Gregg <notifications@github.com>
wrote:

> Oh.. there is probably an out of memory error somewhere. Are you blocking
> in memory? Or to disk like in the myql_example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/376#issuecomment-92175634>.
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by fgregg** [comment]
So, probably using all of Python memory. Write blocks to disk like in MySQL
examsple.

**Comment by asharma567** [comment]
Should I bother using csvdedupe from command line then? or is it even
possible using it?
ᐧ

On Sun, Apr 12, 2015 at 7:53 PM, Forest Gregg <notifications@github.com>
wrote:

> So, probably using all of Python memory. Write blocks to disk like in MySQL
> examsple.
> On Sun, Apr 12, 2015 at 9:46 PM Ajay Sharma <notifications@github.com>
> wrote:
>
> > cat input_dedupe_large.csv | csvdedupe --field_names contact_id
> > FirstName_nicks LastName Email Address1 PhoneMobile > output_test_lrg.csv
> > ......128 mb file
> > ᐧ
> >
> > On Sun, Apr 12, 2015 at 7:37 PM, Forest Gregg <notifications@github.com>
> > wrote:
> >
> > > Oh.. there is probably an out of memory error somewhere. Are you
> blocking
> > > in memory? Or to disk like in the myql_example?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/datamade/dedupe/issues/376#issuecomment-92175634>.
> > >
> >
> >
> >
> > --
> > Github <https://github.com/asharma567/> | LinkedIn
> > <http://www.linkedin.com/in/mrasharma/>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/datamade/dedupe/issues/376#issuecomment-92176417>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/376#issuecomment-92178306>.
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by asharma567** [comment]
I think there's an issue with csv dedupe... in any case I'll refer to your
mysql example

head -100 input_dedupe_large.csv | csvdedupe --field_names contact_id
FirstName_nicks LastName Email Address1 PhoneMobile > output_test_lrg.csv

Traceback (most recent call last):

  File "/Users/asharma.tmp/anaconda/bin/csvdedupe", line 5, in <module>

    from pkg_resources import load_entry_point

  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3057, in <module>

    working_set = WorkingSet._build_master()

  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 641, in _build_master

    return cls._build_from_requirements(__requires__)

  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 654, in _build_from_requirements

    dists = ws.resolve(reqs, Environment())

  File
"/Users/asharma.tmp/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 827, in resolve

    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'dedupe==0.7.3.2' distribution was
not found and is required by csvdedupe
ᐧ

On Sun, Apr 12, 2015 at 7:54 PM, Ajay Sharma <asharma567567@gmail.com>
wrote:

> Should I bother using csvdedupe from command line then? or is it even
> possible using it?
> ᐧ
>
> On Sun, Apr 12, 2015 at 7:53 PM, Forest Gregg <notifications@github.com>
> wrote:
>
>> So, probably using all of Python memory. Write blocks to disk like in
>> MySQL
>> examsple.
>> On Sun, Apr 12, 2015 at 9:46 PM Ajay Sharma <notifications@github.com>
>> wrote:
>>
>> > cat input_dedupe_large.csv | csvdedupe --field_names contact_id
>> > FirstName_nicks LastName Email Address1 PhoneMobile >
>> output_test_lrg.csv
>> > ......128 mb file
>> > ᐧ
>> >
>> > On Sun, Apr 12, 2015 at 7:37 PM, Forest Gregg <notifications@github.com
>> >
>> > wrote:
>> >
>> > > Oh.. there is probably an out of memory error somewhere. Are you
>> blocking
>> > > in memory? Or to disk like in the myql_example?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/datamade/dedupe/issues/376#issuecomment-92175634
>> >.
>> > >
>> >
>> >
>> >
>> > --
>> > Github <https://github.com/asharma567/> | LinkedIn
>> > <http://www.linkedin.com/in/mrasharma/>
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/datamade/dedupe/issues/376#issuecomment-92176417>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/datamade/dedupe/issues/376#issuecomment-92178306>.
>>
>
>
>
> --
> Github <https://github.com/asharma567/> | LinkedIn
> <http://www.linkedin.com/in/mrasharma/>
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>
