### ISSUE TITLE
comparator for name rarity

### ISSUE THREAD

**Issue by lminer** [datamade/dedupe#392]
Let's say I have a measure of last name frequency. Would be nice if pairs were more likely to be matched if their names were less frequent. It's unclear how to add this as a variable as this isn't something that easily maps into the concept of proximity.

I assume that closer to 0 = more proximate, so am trying the sum of the logs of the two values...

**Comment by fgregg** [comment]
I've tried this a few different ways. To me, the most attractive approach is to calculate the probability that these two field value would be chosen at random, and then interact that with the string distance (or other distance) between the fields.

**Comment by lminer** [comment]
hmm. so right now I'm taking the sum of the logs of the frequencies and also including an interaction with the name as a String type. Sounds like essentially the same thing.

**Comment by fgregg** [comment]
Yup. How is that working?

**Comment by lminer** [comment]
Seems to be working well!
