### ISSUE TITLE
Ignored exception in affinegap.affinegap.normalizedAffineGapDistance

### ISSUE THREAD

**Issue by lminer** [datamade/dedupe#397]
Getting the error below in a bunch of locations: loading in sample data, loading in pre-labeled training data, training, etc. Is this because there are `None` values in my data? Should I be worried?

```python
Exception TypeError: "object of type 'NoneType' has no len()" in 'affinegap.affinegap.normalizedAffineGapDistance' ignored
```

**Comment by fgregg** [comment]
Yes. You should represent missing data as an empty string ''

**Comment by lminer** [comment]
Hmm difficult to do when using a dict comprehension to read in the sample like `{i: row for i, row in enumerate(c)}` . Don't want to modify the data in the database and don't want the extra expense of iterating through each row in search of a null value. Will it hurt my results to leave this in?

**Comment by fgregg** [comment]
It will hurt your results.

**Comment by fgregg** [comment]
The way I handle this is through a SQL statement

like IFNULL(name, '')

**Comment by lminer** [comment]
That's what I was looking into. Will this hurt me if the type is Price or longlat?

**Comment by fgregg** [comment]
Yes. the null val for Price is 0
the the null val for lat long is (0,0)

I've been thinking about having dedupe use None as the missing value
indicator.
