### ISSUE TITLE
using training file with django fails on JSON decode

### ISSUE THREAD

**Issue by dbinetti** [datamade/dedupe#399]
first, great library -- thanks for creating.

second, i'm using this with django, which is going swimmingly for all but the file i/o on the training data.  I can save the file OK, but I can't read the training data back into dedupe when needed.  as best as I can tell, django is decoding the json object before it's sent to dedupe -- thus I am getting a `JSONDecodeError: Expecting value: line 1 column 1 (char 0)` when trying to read the file.  

i'm afraid I'm not good enough to mess with the internals (or even understand fully what's going on here) but I figured I'd start by filing an issue and see what happens from there.

as an aside, now that django can easily handle native json objects, perhaps you could provide a method that would allow us to handle them directly?  many thanks...

**Comment by dbinetti** [comment]
By 'using with django' I mean that I am using dedupe within a django app.  (forgive me if this is obvious, but django is a python-based web app framework and can be found at http://djangoproject.com)

part of the django framework is the ability to save files within the context of the framework.  so, in this instance, I am producing a dedupe training file and then saving it to the filesystem [using the django methods for doing so]  (https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.fields.files.FieldFile.save)  

When I look at the resulting file in the filesystem, it appears exactly how I expect: properly formatted JSON, in the training syntax.

However, when I try to access the file, within a django app [using the methods to open a file] (https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.fields.files.FieldFile.open), I get the error that I demonstrated before.

I assumed (perhaps naively) that using `dedupe` within the context of a django app was a common pattern and this issue would be obvious.  again, i'm not sure that this is a bug in either dedupe or django; it could simply be an integration issue.  however, I am stuck and it's beyond my ability to even diagnose.  thanks...

**Comment by fgregg** [comment]
Could you provide some code that reproduces this problem?

**Comment by dbinetti** [comment]
Absent a full django installation the code would make no sense.  I will live with it.  Thanks for replying.
