### ISSUE TITLE
No Python 3.x support?

### ISSUE THREAD

**Issue by dannguyen** [datamade/dedupe#403]
I'm guessing "no" since I get this error with Python 3.4:

~~~sh
  File "/Users/dtown/anaconda/lib/python3.4/site-packages/csvdedupe/csvdedupe.py", line 6, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'
~~~

**Comment by fgregg** [comment]
dedupe is python 3 compatible, but csvdedupe needs to be updated in a few
places.

**Comment by fgregg** [comment]
the newest version of csvdedupe on pypi is 3.4 compatible.
