### ISSUE TITLE
Modifying Features from Learning Algorithm (L2 Logistic Regression)

### ISSUE THREAD

**Issue by johnwu93** [datamade/dedupe#404]
Hi guys,

I think your project is awesome and very useful. I was reading the documentation and I am a bit confused about the features that are used for L2 Logistic Regression. Suppose that I am only finding duplicates on one column, which represent corporation names. According to the documentation, it says that strings are compared through the affine gap string distance. Does that mean I only have only one feature for L2 Logistic Regression, which is the  affine gap string distance for the column on corporation names? Is it possible to include other features, such as the TfIdf cosine similarity metric? How can I modify L2 Logistic Regression features so that I can include other string metrics to compare records.

Also, I was reading the affine gap string distance and it is a learnable distance metric(http://www.cs.utexas.edu/~ml/papers/marlin-tr-02.pdf). I was looking through the affine gap distance metric api and it seems that I have to input the parameters of the affine gap string metric manually; it is not learned. Does the dedupe api use a version of the affine gap string to learn appropriate parameter values for a dataset?

Thanks you guys for your help

**Comment by johnwu93** [comment]
Also, I am a bit confused how the binary classifier used for this algorithm is related to the clustering aspect to find duplicates. Do you guys use the probabilistic values of the binary classifier to compute the pairwise distance between each record, which results in a distance matrix and use this matrix to cluster records together?

**Comment by fgregg** [comment]
Where did you read that?

There are many different types of comparisons, and you can define your own: http://dedupe.readthedocs.org/en/latest/Variable-definition.html

The affine gap distance we have been learning is static. We are transitioning (already in master) to an learnable edit distance. We probably won't provide a lot facilities, within dedupe, to train the learnable edit distance. 

As for clustering, did you read: http://dedupe.readthedocs.org/en/latest/Grouping-duplicates.html

**Comment by johnwu93** [comment]
Hi fgregg, thank you for your fast response. 

I see you can use different string metrics. However, what function in dedupe will enable me to use multiple string metrics for one column for logistic regression. I see in an example, you have:

record_distance = (0.5 * string_distance('bob', 'Robert')
                   + 2.0 * string_distance('roberts', 'Roberts')
                   + 2.0 * string_distance('1600 pennsylvania ave.', '1600 Pensylvannia Avenue')
                   + 0.5 * string_distance('555-0123', ''))

However, is it possible to have 

record_distance = (0.5 * string_distance('bob', 'Robert')
                   + 2.0 * string_distance1('roberts', 'Roberts')
                   + 3.0 * string_distance2('roberts', 'Roberts')
                    + 4.0* string_distance3('roberts', 'Roberts')
                   + 2.0 * string_distance('1600 pennsylvania ave.', '1600 Pensylvannia Avenue')
                   + 0.5 * string_distance('555-0123', ''))

If so, how can I do that?

I read the documentation for the clustering, but can you explain how the probabilities between pairs are computed more in detail?

**Comment by fgregg** [comment]
Please look at https://github.com/datamade/dedupe-examples and read the
documentation on variables.

**Comment by arthur-rocha** [comment]
It's not clear at the documentation if the other types of string metrics are used for the logistic regression or only at the blocking step.
