### ISSUE TITLE
Clarify documentation on gazetteer matching

### ISSUE THREAD

**Issue by lminer** [datamade/dedupe#405]
Unclear from doc what matching messy data (with duplicates) to canonical dataset (with no duplicates) means.

In particular, what happens if there are duplicates in the messy data that don't match anything in the canonical dataset? Are these still matched with each other or do they need to also match with the canonical data.

**Comment by fgregg** [comment]
The assumption of the gazetteer is that it includes all valid entities. This is great for things like address matching or other cases when you can have a true canonical list. 

If something in the messy data doesn't match anything in the canonical list then that's all that happens, it just fails to match.

**Comment by lminer** [comment]
So if you want to identify duplicates in the messy data, you need to dedupe the messy data first.

**Comment by fgregg** [comment]
it's hard to say without knowing more about your case but

let's have the records in canonical be 1, 2, 3, 4, 5

and the records in messy be A, B, C, D

if A matches 1
and B matchs 1

then we can conclude that A and B are duplicates.

**Comment by lminer** [comment]
But if A and B match each other but not anything in the canonical set, then they won't be matched. You would need to do an extra round of deduping on the messy data to find these cases.

Might be useful to create a separate class that dedupes the messy data before matching it with the canonical set.

Any suggestions on what I should read to get a clear sense of the gazetteer assumptions? Is the paper this project is based on the best source?

**Comment by fgregg** [comment]
The assumption of the gazetteer is that *all* the valid entries appear in
the canonical set and that they appear once and only once.

The idea that there could be valid matches in the the messy set that do not
match the canonical set is a violation of this assumption.

**Comment by fgregg** [comment]
Could you make a suggestion of how to improve the documentation?

**Comment by lminer** [comment]
Sure thing. How's this?

Gazetteer matching is for matching a 'messy dataset' against a ‘canonical dataset’ with the following assumptions:

- A messy dataset may contain multiple duplicates referring to the same entity in the canonical dataset. 
- A canonical dataset, cannot have any duplicates.

This class is useful for such tasks as matching messy addresses against a clean list. A Gazetteer will not match records in the messy data that match each other but don't match anything in the canonical dataset.
