### ISSUE TITLE
Settings file depends on path of module from which it was trained

### ISSUE THREAD

**Issue by lminer** [datamade/dedupe#406]
I've written a module that trains a Dedupe model and saves the settings. The settings file seems to store the import path of this module. When I changed the path of this module, I was no longer able to import the settings without changing the relevant line in the settings file.

So basically, when trained from the module `base.a.mymodule`, the settings file now contains a line `cbase.a.mymodule`. If I move the module to `base.b.mymodule`, i need to update the line in the settings file to `cbase.b.mymodule`. Otherwise I get the error `Something has gone wrong with loading the settings file`

Edit:
This seems to have to do with custom comparators. The settings file is referencing the custom comparator that I created at this point.

**Comment by fgregg** [comment]
What do you think should happen?

**Comment by lminer** [comment]
Ideally, I suppose, once a model had been trained, the settings file would be self contained and not depend on the import structure of the module calling it...

I'm assuming the problem is that it depends on the custom comparator and so needs to have access to it. Would it be possible to pickle the custom comparator during the settings saving stage?

Apologies if this issue is trivial and misguided. Very happy, impressed, and grateful for dedupe. Only bringing this up because I thought it might be helpful in case the behavior was not expected.

**Comment by fgregg** [comment]
We depend upon pickling, which has this behavior. If you want to make a PR that has a different behavior I'll take a look at it. Closing for now.
