### ISSUE TITLE
API documentation for TF-IDF blocking

### ISSUE THREAD

**Issue by jacobdr** [datamade/dedupe#409]
Was reading through the [mysql example](http://open-city.github.io/dedupe/doc/mysql_example.html#section-21) and couldn't seem to find any documentation for the `tfidf_fields` on the blocker object, referenced in the example as `deduper.blocker.tfidf_fields`.

Is there an API reference that I am missing?

Thanks,
Jacob

**Comment by fgregg** [comment]
Sorry that you ran across some out of date documentation. This is what you want http://datamade.github.io/dedupe-examples/docs/mysql_example.html

I've gotten the out of date documentation deleted now.
