### ISSUE TITLE
Support for Address

### ISSUE THREAD

**Issue by rakeshmalpani** [datamade/dedupe#414]
Hi, I have been using the dedupe component for a few months, I did an upgrade and I noticed that the address.py class in not present in variable package. Is this a bug, or is it that the support for address field type has been removed.

**Comment by fgregg** [comment]
It's never been in dedupe, but always available as an add on.
https://pypi.python.org/pypi/dedupe-variable-address

On Mon, Sep 14, 2015 at 4:55 PM, rakeshmalpani <notifications@github.com>
wrote:

> Hi, I have been using the dedupe component for a few months, I did an
> upgrade and I noticed that the address.py class in not present in variable
> package. Is this a bug, or is it that the support for address field type
> has been removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/414>.
>



-- 
773.888.2718

**Comment by rakeshmalpani** [comment]
Hi Greg, thanks very much for that, I missed installing the

**Comment by rakeshmalpani** [comment]
Hi Greg, thanks very much for that.. I missed installing/updating the variable-address package. I just installed/updated the address package (along with dedupe package itself). It works like a charm now. Thanks very much.

Regards,
Rakesh.
