### ISSUE TITLE
What does WARNING:dedupe.training:Ran out of predicates mean?

### ISSUE THREAD

**Issue by Shotgunosine** [datamade/dedupe#415]
I am attempting to train a deduper using data that has been manually clustered. I am just using a single field with the 'Name' type.

train_names is a 1500 item long dictionary with the form:
```{'1': {'Cluster ID': '8061',
  'Id': '1',
  'name': 'ACME, LLC'},...```


The code I am running for the training is:
```fields = [
        {'field' : 'name', 'type': 'Name'}
        ]
deduper = dedupe.Dedupe(fields)

deduper.markPairs(dedupe.trainingDataDedupe(train_names,'Cluster ID'))

deduper.train()```


After running ```dedupe.train()```  I get the following error:
``` WARNING:dedupe.training:Ran out of predicates ```

What does this warning mean and do I need to do anything to remedy it, or can I carry on despite it?

**Comment by fgregg** [comment]
You can carry on. 

Dedupe tries to find blocking rules that will work well with your data. Sometimes it can't find great ones, and you'll get this warning. It means that there are some pairs of true records that you dedupe may never compare.

**Comment by Shotgunosine** [comment]
Thanks for the clarification. Is there any chance that failing to find good blocking rules on the training set would slow things down in finding a threshold or matching on a test dataset?

**Comment by fgregg** [comment]
Yes. If you learn liberal blocking rules you will make many more
comparisons.
