### ISSUE TITLE
incremental dedupe

### ISSUE THREAD

**Issue by kshishir** [datamade/dedupe#421]
Hi,
    I have deduped list and want to run dedupe on a new file and append to the cluster I already created without changing the clusterId.
Is there a way to do that? I do not want to run the dedupe process for all the records again.

Thanks,
Shishir

**Comment by fgregg** [comment]
You can run a Gazetteer session against your already dedupe file.

**Comment by kshishir** [comment]
I tried gazetteer match a few times but I am not able to get multiple matches from my messy data input. I have a dedupe output and I am taking clusterId and canonical name from the output and trying to get matches with messy data which could have multiple matches for a canonical name. I am only getting one record match, similar to the record-linkage. Do you have an example of gazetteer match like other matching examples?
