### ISSUE TITLE
Model fields that require a corpus cannot be searched for values not in the corpus

### ISSUE THREAD

**Issue by evz** [datamade/dedupe#422]
When using a Gazetteer instance to find matches in a dataset that has a model that uses a field that requires a corpus, if the value being searched for is not already in the corpus, Dedupe will return an error.

**Comment by fgregg** [comment]
Closed by https://github.com/datamade/fuzzycategory/commit/775db757ac4ba5bb710b46a2c52eefe94d19f08f
