### ISSUE TITLE
python3.4 multiprocessing

### ISSUE THREAD

**Issue by lucaswiser** [datamade/dedupe#430]
As documented here https://pythonhosted.org/poppy/performance.html the issue with multiprocessing on os-x is fixed in python 3.4. Can someone confirm that this is in fact correct? If it is, can we change dedupe/backport.py:17 to check if python > 3.4 is being used and then allow multiprocessing?

**Comment by fgregg** [comment]
Python 3.4 introduced new models for multiprocessing, one of which
("spawn") is compatible with Accelerate. Unfortunately, it's not simple to
just switch the multiprocessing modes from "fork" (the default and what we
use) to "spawn".

If this is something that you would like to look into, I'd welcome that.

On Mon, Dec 7, 2015 at 3:03 PM, lucaswiser <notifications@github.com> wrote:

> As documented here https://pythonhosted.org/poppy/performance.html the
> issue with multiprocessing on os-x is fixed in python 3.4. Can someone
> confirm that this is in fact correct? If it is, can we change
> dedupe/backport.py:17 to check if python > 3.4 is being used and then allow
> multiprocessing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/430>.
>



-- 
773.888.2718

**Comment by lucaswiser** [comment]
Ok I will look into it and see what can be done.
