### ISSUE TITLE
os-x multiprocessing

### ISSUE THREAD

**Issue by lucaswiser** [datamade/dedupe#433]
Hey so following the documentation I couldn't get numpy to not be linked to the accelerate framework. I finally got it to work, by changing the site.cfg to:

[DEFAULT]
library_dirs = /path/to/openblas/lib
include_dirs = /path/to/openblas/include

[atlas]
atlas_libs = openblas
libraries = openblas

[openblas]
libraries = openblas
library_dirs =  /path/to/openblas/lib
include_dirs =  /path/to/openblas/include

as found in this tutorial https://leemendelowitz.github.io/blog/installing-numpy-with-openblas.html

I think the [atlas] part is what I was missing before. Maybe this should be added to the docs?

I also ran these 2 commands before I built
 unset CPPFLAGS
unset LDFLAGS

but I don't know if they actually did anything.

**Comment by fgregg** [comment]
Would you mind submitting a PR.
