### ISSUE TITLE
Fast approximated dictionary indexes 

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe#436]
- [Improved Fast Similarity Search in Dictionaries](http://arxiv.org/pdf/1008.1191)
- An geocoder based on some of this work https://github.com/mapbox/carmen

**Comment by fgregg** [comment]
* http://stevehanov.ca/blog/index.php?id=119
* http://fastss.csg.uzh.ch/ifi-2007.02.pdf
http://fastss.csg.uzh.ch/

**Comment by fgregg** [comment]
@immerlernen, @mattandahalfew @bahadasx, Welcome aboard!

So, right now we are using one type of index blocking rule, which is based upon the tf-idf similarity of the tokens of the query string to the indexes strings.

The code for this is in https://github.com/datamade/dedupe/blob/master/dedupe/index.py and https://github.com/datamade/dedupe/blob/master/dedupe/tfidf.py

The key methods are https://github.com/datamade/dedupe/blob/master/dedupe/tfidf.py#L22
and https://github.com/datamade/dedupe/blob/master/dedupe/tfidf.py#L34

Here are some tests to get you familiar: https://github.com/datamade/dedupe/blob/master/tests/test_tfidf.py

I would start by playing with the code behind the fast approximate dictionary searches that are in these links and figuring out how to create the indexes (or functionally equivalent data structure) and how to do searches.

**Comment by fgregg** [comment]
@immerlen, @mattandahalfew, @bahadasx how does that sound?

**Comment by bahadasx** [comment]
@fgregg Thanks!  That is very helpful. 👍

**Comment by fgregg** [comment]
@immerlernen, @mattandahalfew, @bahadasx any updates?

**Comment by mattandahalfew** [comment]
So a TfIdfIndex contains a CanopyIndex called _index, which contains a CosineIndex called index. _index contains one kind of CanopyLexicon called lexicon. However, index contains two CanopyLexicons called _lexicon and lexicon. I am at the step of understanding the role of these different indexes and lexicons.

**Comment by fgregg** [comment]
Where is "_lexicon"

**Comment by mattandahalfew** [comment]
Line 81 of cosineindex.py

**Comment by fgregg** [comment]
This is getting into some deep implementation details that may be of mild relevance, since you won't be using code from zope.index anyway. The 'indexing' and 'querying' interfaces are likely to be very different for the fast approximated dictionaries.

At a high level, we are building an index from a list of documents, once we have that built, we can query that index. 

This is like 'add' method for TinyFasSS: https://github.com/fujimotos/TinyFastSS/blob/master/fastss.py#L177

and the 'query' method https://github.com/fujimotos/TinyFastSS/blob/master/fastss.py#L187

**Comment by fgregg** [comment]
Any updates?

**Comment by mattandahalfew** [comment]
We are going to replace lines 67 and 71 of blocking.py. We're creating a C module using [these methods](https://docs.python.org/2/extending/extending.html). Line 67 will add words to a list of words in the C module. Line 71 will create a tree-structured dictionary from this list, which will use a depth first search algorithm and be queried one letter at a time. This generates a list of words that are d distance away from the query word.

We will also replace line 157 of predicates.py, which performs the queries on the dictionary one word at a time.

Looking at csv_example from dedupe's github, I think this plan would increase the speed of dedupe by orders of magnitude. At the moment, we've accomplished putting individual words into the C module and reading them accurately.

**Comment by fgregg** [comment]
Cool! Just so you know, I don't want to replace the current, token based predicates. I want to add the character distance based methods. 

Is your code anywhere I can see.

**Comment by fgregg** [comment]
Any updates?

**Comment by mattandahalfew** [comment]
No updates yet. I'm still working on it. Balancing all my other "free-time" projects with this one, I estimate this will be finished in 3-6 months.

**Comment by fgregg** [comment]
thanks for that eta

**Comment by mattandahalfew** [comment]
I have an update for you. I wrote the code in C that will perform the Levenshtein search quickly using a graph search algorithm. Right now it works in Python 2.7 and I have to add support for 3.x. As an example, I added some words to the dictionary and then looked up the word, "foxes", specifying a maximum allowed Levenshtein distance of 2. I put the current version of my code on github: https://github.com/mattandahalfew/Levenshtein_search/blob/master/tree_struct.c
Adding: foxes
Adding: fixes
Adding: faxes
Adding: fonts
Adding: first
Adding: focus
Adding: boxes
Adding: Knox
Adding: font
Adding: rocks
Adding: focused
Adding: locks
Adding: sox
Adding: sixes
Adding: oxen
Adding: sexes
Adding: Texas
Adding: fixed
Adding: fixer
Adding: fives
Adding: faves
Adding: fave
Adding: foe
Adding: focuses
Adding: affix
Adding: foxy
Adding: fox
Adding: focuser
Adding: focused
Adding: fax
Adding: fix
Adding: flex
Adding: flexes
Adding: flax
Adding: foxier
Python argument: foxes
Lookup word: foxes

Python argument: foxes
fixes
faxes
fox
fives
faves
focus
foe
fixed
fixer
fonts
sixes
foxes
oxen
flexes
foxier
sexes
foxy
boxes

**Comment by fgregg** [comment]
Very cool! Look forward to playing with this!

**Comment by mattandahalfew** [comment]
The multi-platform version of the search algorithm is ready and posted on https://github.com/mattandahalfew/Levenshtein_search

I'm very curious to see how it does in the real world!

**Comment by mattandahalfew** [comment]
The way this can work is that the TF-IDF can be improved upon by including words that are approximately similar to the query word. Term frequencies for a document are now easy to compute using this module. Term frequencies for each similar word can be added together along with those from the query word, albeit with with penalties proportional to the edit distance from the query word. IDF can do something similar with a smaller edit distance to avoid "saturating" this statistic.

**Comment by fgregg** [comment]
cool, do you want to code that up?

**Comment by mattandahalfew** [comment]
What applications did you have in mind for this? I see that you currently take an address like "1 N. Ogden Ave", break it up into 2-grams and treat those as words. Did you try taking the entire address and treating that as a word? That seems simpler at first.

**Comment by fgregg** [comment]
If you treated the whole address as a single word, then tf-idf just reduces to exact match? I think I don't understand what you are asking?

**Comment by mattandahalfew** [comment]
If we treated the whole address as a single word and did a distance-based search on that, it would not use TF-IDF, but would retrieve other addresses that are very similar. In this case, there is only one document made up of all the addresses in the data set.

**Comment by fgregg** [comment]
Yes. That was the original reason why I wanted a fast approximate string index. However, in https://github.com/datamade/dedupe/issues/436#issuecomment-255528910 it sounds like you were talking about a Soft-TFIDF implementation, http://secondstring.sourceforge.net/javadoc/com/wcohen/ss/SoftTFIDF.html

**Comment by mattandahalfew** [comment]
Yes, I was talking about a soft-TFIDF implementation. That would be cool to do. Has the non-tfidf method already been started since that was your original reason for a fast approx. string index?

**Comment by fgregg** [comment]
I haven't started that. It's basically going to be copying and adapting the pattern of the tf-idf index predicates https://github.com/datamade/dedupe/blob/master/dedupe/predicates.py#L91-L173

**Comment by fgregg** [comment]
Feel free to take a swing at it, if you like.

**Comment by mattandahalfew** [comment]
At the end of this week I might have some time to start looking at it.

**Comment by fgregg** [comment]
Great! Look forward to it.

**Comment by fgregg** [comment]
Hi @mattandahalfew, I started working on this, but ran into an architectural issue.

We need to make separate indexes for every field. For example, if we have a record set like.

```
{1 : {'name' : 'Stephen', 'address' : '1600 Pennsylvania'},
 2: {'name' : 'Steve', 'address' : '1600 Pennslyvanniia'}}```

Then we would want an index for the `name` field and a separate index for the `address` field.

Right now, your code has only one single, module level global index. Through hackery we could make that work, but it would be *much* better if we could have multiple, separable indexes.

**Comment by mattandahalfew** [comment]
I added the ability to have separate indexes. The way you would do it is like this:
```python
import Levenshtein_search

#The record set will be called 'record_set'
record_set = {1 : {'name' : 'Stephen', 'address' : '1600 Pennsylvania'}, 2: {'name' : 'Steve', 'address' : '1600 Pennslyvanniia'}}
#The list of field names will be called 'record_set_keys'
record_set_keys = list(record_set[1].keys())
#The dictionary 'keys2idx' will store the numeric index of each key
keys2idx = {}

#The 'populate_wordset' function outputs the numeric index for every field. Separate indexes are initialized here. -1 in the first argument means 'create a new index'.
for key in record_set_keys:
    keys2idx[key] = Levenshtein_search.populate_wordset(-1,[])

#Add records. The first argument to populate_wordset is the index of your field
for record in record_set:
    for key in record_set_keys:
        Levenshtein_search.populate_wordset(keys2idx[key],[record_set[record][key]])
        
similar_address = Levenshtein_search.lookup(keys2idx['address'],'1600 Pennsylvania',4)
#similar_address = [['1600 Pennsylvania', 0, 0.5], ['1600 Pennslyvanniia', 4, 0.5]]
similar_name = Levenshtein_search.lookup(keys2idx['address'],'1600 Pennsylvania',4)
#similar_name = []
```

**Comment by fgregg** [comment]
This can work for testing purposes, but we will need a way to be able to create distinct index object for the full version.

**Comment by mattandahalfew** [comment]
Ah ok, I'll look in to how to do that

**Comment by fgregg** [comment]
@mattandahalfew have you had any time to look at this?

**Comment by mattandahalfew** [comment]
I made the search algorithm significantly faster and added the ability to add and remove words on an individual basis. You can download the latest update.

**Comment by mattandahalfew** [comment]
Garbage collection would use the __del__ function, which would call the module's clear_wordset(idx) function

**Comment by fgregg** [comment]
This is fantastic! So, to wrap this up, we binary builds for windows and macs available on pypi. 

Here's an example of how this can be done: 

* https://github.com/datamade/pyhacrf/blob/master/appveyor.yml
* https://github.com/datamade/pyhacrf/blob/master/.travis.yml

If you set accounts on [travis](https://travis-ci.org/), [appveyor](https://ci.appveyor.com/), and [pypi](http://peterdowns.com/posts/first-time-with-pypi.html). I can help you with this.

**Comment by mattandahalfew** [comment]
Ok, I set up my accounts and am ready for you to help me with this.

**Comment by mattandahalfew** [comment]
Right now I haven't been able to get it to compile on OS X but everything else works fine.

**Comment by fgregg** [comment]
K. I'll take a look later today.

**Comment by xguse** [comment]
does this really not work on python 3?
