### ISSUE TITLE
Gazetteer match

### ISSUE THREAD

**Issue by kshishir** [datamade/dedupe#439]
Can you give me an example of how to run a gazetteer match? I followed the documentation but my results are same as record linkage (1:1) match. 
I want to run gazetteer run for incremental runs when I get new dataset to match against the dataset I have already deduped. 
Thank you.

**Comment by kshishir** [comment]
here is my code that i modified from the examples to get Gazetteer records match.
Could you let me know what I am missing.

[gazetteer_match.txt](https://github.com/datamade/dedupe/files/113005/gazetteer_match.txt)

**Comment by fgregg** [comment]
I don't think you are missing anything.
