### ISSUE TITLE
weighted variables

### ISSUE THREAD

**Issue by kshishir** [datamade/dedupe#440]
Is it possible to assign match weight to the variables used to match?
Eg: if i am using Name, Address, DOB, Gender, SSN
SSN match has more weight than Name.
SSN and DOB match has more than Name and DOB.

Any suggestion?

**Comment by fgregg** [comment]
One of the key points of dedupe is that these weights will be assigned
automatically using trainging data. Are you not getting the weights you
want?

**Comment by kshishir** [comment]
Thanks! 
based on the input source, different combination of variables could have different weights.
I was wondering if it can be set manually when we list fields instead of using different training/settings for different sources.
