### ISSUE TITLE
confidence score and similar name cluster

### ISSUE THREAD

**Issue by kshishir** [datamade/dedupe#441]
Hi,
    I tried dedupe on a small sample dataset and tried to dedupe it by name:
There were 1000 records and I trained for about 150 records.
(modified the code to give me count of number of training records completed to keep track)

I am seeing some results where similar names are not grouped together. E.g.

First, only two names would group together:
cluster_id	score	id	name
19	0.994552851	526		Enterprise
19	0.994552851	567		Enterprise
300		                584		Enterprise

After several training, i finally grouped them together,but the score for two records are different than the other even though they have same name.
cluster_id	score	id	name
19	0.98516196	526		Enterprise
19	0.49258098	567		Enterprise
19	0.49258098	584		Enterprise

I saw this issue in a few other records. 
Do you know why I might be getting this?

**Comment by fgregg** [comment]
This was fixed by https://github.com/datamade/dedupe/commit/fb31783c0f93f1d9cddb12002df039987e36f76e
