### ISSUE TITLE
Error when trying to writeTraining()

### ISSUE THREAD

**Issue by lawli3t** [datamade/dedupe#443]
I am trying to write my training results to a file, where i encounter the following error:

> Traceback (most recent call last):  
>   File "link_data.py", line 60, in <module>  
>     linker.save_data(files)  
>   File "/vagrant/../src/linker.py", line 24, in save_data
>     self.linker.writeTraining(f)
>   File "/vagrant/../venv/lib/python3.4/site-packages/dedupe/api.py", line 736, in 
> writeTraining
>     ensure_ascii=True)
>   File "/vagrant/../venv/lib/python3.4/site-packages/simplejson/__init__.py", line 277, in dump
>     fp.write(chunk)
> TypeError: 'str' does not support the buffer interface

I am using Python 3.4.3 on Ubuntu.

Do i have  to submit the strings in the item dicts in a special form, or whats the problem here? Couldnt find anything

**Comment by fgregg** [comment]
I don't now anything about your "save_data" method. This looks to me like
you did not open the file correctly.

**Comment by lawli3t** [comment]
sry, here it is

`    def save_data(self, files):
        with open(files[0], "wb") as f:
            self.linker.writeTraining(f)
        with open(files[1], "wb") as f:
            self.linker.writeSetting(f)`

**Comment by fgregg** [comment]
you need

```python
with open(files[0], "w") as f:
     self.linker.writeTraining(f)
```

**Comment by lawli3t** [comment]
okay, in the [docs](http://dedupe.readthedocs.org/en/latest/API-documentation.html#Gazetteer.writeTraining) it says "wb" though, so there might be an error there. Thank you!

**Comment by fgregg** [comment]
Fixed in the docs.
