### ISSUE TITLE
Investigating adaptive blocking

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe#444]
Because of @vm-wylbur work on [Michelson's approach to adaptive selection of blocking rules](https://hrdag.org/tech-notes/adaptive-blocking-writeup-3.html#What-I-actually-did), I've been reinvestigating different approaches learning blocking rules. In particular, I've been thinking about algorithms and cost functions.

## Algorithms
Both Bilenko and Michelson use a greedy algorithms, and Bilenko provides an error bound for his approach. However, Paul Miettenan, in [his dissertation on Binary Matrix Factorization](https://helda.helsinki.fi/bitstream/handle/10138/21376/matrixde.pdf?sequence=1) describes a iterative algorithm for Red Blue Set Cover Problem that has no error bounds but empirically dominates the Bilenko algorithm by wide margins. 

These problems may also be fruitfully addressed by branch and bound algorithms. Here's how the eminent Peter Norvig used them in a simpler Set Cover problem: http://nbviewer.jupyter.org/url/norvig.com/ipython/xkcd1313-part2.ipynb?create=1#Searching:-Branch-and-Bound-Search

I'd like to investigate both Miettenan's iterative algorithm and branch and bound.

## Cost Functions
There are three existing formulations used for the problem of adaptive blocking.
* Red Blue Set Cover: Find a set of rules that covers all coreferent pairs and a minimum number of distinct pairs
* Partial Set Cover: Find a set of rules that minimizes the cost of uncovered coreferent pairs and the cost of covered distinct pairs.
* Michelson: Find a set of rules that cover the maximum number of coreferent pairs and the minimum number of pairs

It's clear that (# of distinct pairs converges)/(# of pairs) converges to 1 as the size of datasets increase. I'm not sure that this true for pairs covered by blocking rules, (or even how to formulate that in a well posed way), but I think it is.

Assuming it is, then these three formulations are effectively equivalent for large data. If that's so, then Michelson's approach has a strong advantage over the others.  It's very difficult to estimate the number of distinct pairs covered by a blocking rule, but easy to estimate the total number of pairs covered by a blocking rule.

**Comment by vm-wylbur** [comment]
This is extremely interesting. I look forward to reading what you find! On redundant rules, I've played a bit with shuffling the discovered rule order to see if any can be dropped, but I didn't get much improvement. A penalty might help.

**Comment by fgregg** [comment]
I'll keep my notes here. Congrats on your big story today, btw http://arstechnica.co.uk/security/2016/02/the-nsas-skynet-program-may-be-killing-thousands-of-innocent-people/.

**Comment by vm-wylbur** [comment]
I'll keep an eye on the work here, very interesting stuff, good luck. I've got some new stuff I'll put up in the next few weeks on an ensemble classifier using the weighted averages of a set of dissimilar classifiers, might be interesting to you. I'm always fascinated by the cases that different classifiers put in different parts of the scoring space. And on the NSA stuff, well, yeah. I *love* good science. Bad science is bad, esp when it's used to kill people.

**Comment by fgregg** [comment]
To implement this we'll do something like this:

```python
predicate_cover = {}
block_index = {}
for predicate in blocker.predicates :
     for record_id, record in records :
         blocks = predicate(record)
         for block in blocks :
             predicate_cover[predicate][block].add(record_id)
             block_index[record_id][predicate].add(block)

for predicate_a, predicate_b in combinations(blocker.predicates, 2) :
      compound_predicate = (predicate_a, predicate_b)
      for record_id, record in records :
          blocks_a = block_index[record_id][predicate_a] 
          blocks_b = block_index[record_id][predicate_b] 
        
          for a, b in product(blocks_a, blocks_b) :
              if (a,b) not in predicate_cover[compound_predicate] :
                  predicate_cover[compound_predicate][(a,b)] = predicate_cover[predicate_a][a] & predicate_cover[predicate_b][b]
```

**Comment by fgregg** [comment]
thanks for the inspiration @vm-wylbur

**Comment by vm-wylbur** [comment]
Super cool, I look forward to digging in when I get back to hack mode. Hey, I hear DataMade is maybe working with a project I work with -- the Security Force Monitor Project. I'm on the adv board. I look forward to working together more.
