### ISSUE TITLE
Get error about dedupe.sampling

### ISSUE THREAD

**Issue by aglorios** [datamade/dedupe#449]
When I run csv_example.py (converted to ipynb) in ipython. I've installed dedupe.

**Comment by fgregg** [comment]
Hi @aglorios I think this is a duplicate of https://github.com/datamade/dedupe/issues/371 Can you try what people tried over there.

**Comment by aglorios** [comment]
Hi Forest,
I saw that thread but it looks like no one solved, only said it was an
ipython problem.

Thanks,

Alex

On Friday, March 11, 2016, Forest Gregg <notifications@github.com> wrote:

> Hi @aglorios <https://github.com/aglorios> I think this is a duplicate of
> #371 <https://github.com/datamade/dedupe/issues/371> Can you try what
> people tried over there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe/issues/449#issuecomment-195359531>.
>


-- 
Best wishes,

Alex

Website:    www.alexandraglorioso.com
twitter:      @aglorios
cell:          347.443.4890

**Comment by fgregg** [comment]
Yes, it wasn't solved, but people do describe a work around. Does that work
around work for you?
