### ISSUE TITLE
clustering Large Dataset

### ISSUE THREAD

**Issue by kshishir** [datamade/dedupe#452]
Hi,
   I am trying to run the dedupe process on a large dataset (2M) records and 8 fields.
I tried both mysql and pgsql examples for dedupe.
Blocking takes about 30 mins for all records.
Everything works file until the clustering.
I left the process running for 2 days and it did not even get to the first 10K records.
I created a small sample of 500 records and it ran in about 2 minutes.
I am running the process on a linux machine with 32GB memory.

Is 2M records too large for 32GB machine? Is there anything I should be doing to optimize the process for larger dataset?

**Comment by fgregg** [comment]
Did you run out of memory? 

Assuming that you didn't run out of memory, I would expect that you learned blocking rules that are too liberal. That is, you learned blocking rules that cause you to compare too many records that are actually distinct.

You can alter that by changing two parameters in the train method. http://dedupe.readthedocs.org/en/latest/API-documentation.html#Dedupe.train, `ppc` and `uncovered_dupes`




If I had to guess, I'd

**Comment by fgregg** [comment]
Actually, I'm confused by what you mean by "first 10K records." What do you mean by that?

**Comment by kshishir** [comment]
I did not get out of memory error. When running the large file,  I checked the memory usage, it varied from 28GB to 14GB at different times. 

I trained about 200 records, which could have been an issue.  

By first 10K I mean, when clustering, in the candidates_gen() function time taken for every 10K blocks in printed. It did not get to the first 10K info print. 

If there is no other optimization required then I will retrain the dataset more. 
Just curious, What is the largest dataset you have run dedupe on? and what configurations were you using?

**Comment by fgregg** [comment]
Blocks != records. One block could contain millions and millions of record pairs.

I wouldn't add more training data, I would try adjusting the arguments to train that i mentioned above.

I would also recommend upgrading to the newest version of dedupe, we made some changes to blocking that can help you.

We have run dedupe on data that is bigger than yours, and we adjusted those arguments.

**Comment by kshishir** [comment]
Yes, I am currently running 1.3.7 version. I updated it recently.
I will make some changes in the train arguments and let you know.

Thanks!

**Comment by kshishir** [comment]
I spent some time on it I am still not able to run it on 2M records. 
I changed ppc from 0.1 to 0.00001 and even less and pud from 0.9 to 0.01. several different combinations.
For some combination, the process ran for first 100 blocks from 900 secs to 3000 seconds but did not go further than that.
I also updated to the latest 1.3.8 version to use pud parameter.
I also changed the number of fields used for dedupe from 8 to 5.
Anything else I can try to speed up the process?

**Comment by fgregg** [comment]
Can you post your code? Are you able to post any of the data?

**Comment by kshishir** [comment]
I cannot post the data. 
here is the code. It is almost the same as pgsql example with some modifications for fields and 8.4 version of postgresql. 
I also tried it with mysql example with same issue.

[pgsql_sample.txt](https://github.com/datamade/dedupe/files/178652/pgsql_sample.txt)

**Comment by fgregg** [comment]
I don't see anything obviously wrong. Without the data, I don't think I can help you further. 

If you need to preserve control of the data, maybe we could help you further if you engaged my company http://datamade.us/contact-us/index.html and we could deal with your data under a contract.

Two million is definitely not too big.
