### ISSUE TITLE
Problem with importing dedupe in windows, using python 3.4

### ISSUE THREAD

**Issue by sushiyan** [datamade/dedupe#455]
Hi, 

I managed to install dedupe on my windows without any error. However, when i tried to import it inside python 3.4, i get the following error:

UnicodeDecodeError                        Traceback (most recent call last)

----> 6 from dedupe._init import *
----> 1 from dedupe.api import StaticDedupe, Dedupe
---> 21 import rlr
----> 1 from .lr import RegularizedLogisticRegression
----> 2 import lbfgs
----> 7 from ._lowlevel import LBFGS, LBFGSError

lbfgs/_lowlevel.pyx in init lbfgs._lowlevel (lbfgs/_lowlevel.c:8093)()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte

Can someone please let me know how to resolve this error?

Many thanks.

**Comment by fgregg** [comment]
Do you have a 32 or 64 bit machine?

**Comment by fgregg** [comment]
Can't reproduce.
