### ISSUE TITLE
Interaction variable is not a named variable in the variable definition

### ISSUE THREAD

**Issue by doodnayr** [datamade/dedupe#462]
I have fields defined as:

fields = [
    {'field' : 'FirstName', 'type': 'String', 'has missing' : False},
    {'field' : 'MiddleName', 'type': 'String', 'has missing' : True},
    {'field' : 'LastName', 'type': 'String', 'has missing' : False},
    {'field' : 'DOB', 'type': 'String', 'has missing' : True},
    {'field' : 'Gender', 'type': 'Categorical', 'categories' : ['m', 'f'], 'has missing' : True},
    {'field' : 'Phone', 'type': 'String', 'has missing' : True},
    {'type': 'Interaction', 'interaction variables': ['DOB', 'Phone']}
]

I am getting "The interaction variable DOB is not a named variable in the variable definition."

Function interactions(definitions, primary_fields) in datamodel.py has the following line:
field_d = {field.name : field for field in primary_fields}

This field_d object ultimately gets passed to the field_model argument of atomicInteractions(self, interactions, field_model) in interaction.py, where the existence in field_model of each interaction variable name is checked.

I printed the value of field_d/field_model, and it makes no sense to me and obviously doesn't contain the key "DOB":

{'(MiddleName: String)': (MiddleName: String), '(Gender: Categorical)': (Gender: Categorical), '(LastName: String)': (LastName: String), '(Phone: String)': (Phone: String), '(FirstName: String)': (FirstName: String), '(DOB: String)': (DOB: String)}

Is this a bug or am I missing something? I upgraded to the most recent version.

**Comment by doodnayr** [comment]
Sorry, I was looking at an old example that didn't have 'variable name' key in it when defining the fields.

Fantastic library!

**Comment by fgregg** [comment]
Where was the example?

**Comment by doodnayr** [comment]
It's at the bottom of the Missing Data section, so not even about interactions in particular, but it was the example I happened to be using at the time since it had an interaction in it. I should have looked at the example under the Interaction section more carefully.

http://dedupe.readthedocs.org/en/latest/Variable-definition.html#missing-data

**Comment by fgregg** [comment]
Thanks! Fixed now.
