### ISSUE TITLE
Missing values for string types

### ISSUE THREAD

**Issue by semerj** [datamade/dedupe#464]
Hi there! I'm really enjoying using your library and had a question about dealing with missing values for string types. The [documentation](https://dedupe.readthedocs.io/en/v0.5.3.0/Field-definition.html#string-types) says to use empty strings, but this returns `ZeroDivisionError: float division` errors. However, when I replace empty strings with `None` types, it seems to work.

I checked some old issues and saw this:

> Check if your data in any of the fields is an empty string. It should be None instead of empty strings.

It would be great to get a conclusive answer to this. Thanks!

**Comment by fgregg** [comment]
Thanks! Our documentation is out of date. Use None.

**Comment by fgregg** [comment]
That's the documentation for a much older version of dedupe. I deactivated it from readthedocs. Do you remember how you got to it?

**Comment by semerj** [comment]
It was the first hit when searching on Google for "dedupe missing values"

https://dedupe.readthedocs.io/en/v0.5.3.0/Field-definition.html

**Comment by fgregg** [comment]
Okay, bummer. 

Hopefully, google will pick up the right version soon.
