### ISSUE TITLE
Python.h file missing

### ISSUE THREAD

**Issue by janvidpa** [datamade/dedupe#465]
When I try to install dedupe I get the following error:
 In file included from persistent/cPersistence.h:18:0,
                     from persistent/cPersistence.c:19:
    persistent/_compat.h:18:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.

**Comment by fgregg** [comment]
Take a look at the responses here: http://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
