### ISSUE TITLE
Active learner suggestion speed decreases as training increases

### ISSUE THREAD

**Issue by algrebe** [datamade/dedupe#470]
The active learning exposed via `consoleLabel` function, takes a very long time to suggest more pairs for labeling as the number of previous labelled entries increase.

@fgregg mentioned that this is because of cross validation happening every time `markPairs` is called, and one solution is to do the cross validation only once at the end when the training finally happens.

**Comment by fgregg** [comment]
Closed by https://github.com/datamade/dedupe/commit/d074f459b1399a30a27ab3771ae0c0fcfdfef7d5 

You'll also need to upgrade rlr to 2.4
