### ISSUE TITLE
csvdedupe matches only one single record of each csv file

### ISSUE THREAD

**Issue by lvpasquier** [datamade/dedupe#475]
Hi, 

First, i'd like to thank for this very smart library.

I would like to match records between two CSV files. Though, I noticed that once dedupe found a matching pair of record, it won't match some others. 

For example : 

CSV1 : 
'one'
'two'
'three'

CSV2:
1
2
2'
3

What I get as output is something like : 
'one', 1
'two', 2
'three', 3
, 2'

Shouldn't it return something more like :
'one', 1
'two', 2
'two', 2'
'three', 3

thanks for your help.

**Comment by fgregg** [comment]
what is the command you used?

**Comment by lvpasquier** [comment]
The command is the following : 

csvlink 'path/to/my/file1.csv' 'path/to/my/file2.csv' --field_names_1 address zipcode --field_names_2 address zipcode --output_file path/to/my/output.csv

thanks for your time.

**Comment by fgregg** [comment]
csvlink assumes that the each file does not have any duplicates.
