### ISSUE TITLE
Deprecating data_sample argument

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe#476]
Right now, we have two different ways to provide a sample to a dedupe instance. the `data_sample` argument of the initialization method and the `.sample` method. 

This made a certain sense, when the `.sample` method just took a random sample. Often, users have another way to take a random sample without loading all the data into memory, for instance if they have data loaded in the database.

However, a normal random sample isn't all that good because duplicates are much, much rarer then distinct pairs, and the the `.sample` does a lot more stuff to get useful dupes. 

If you have very big data, the better thing would be to give a large random sample of records to the sample method and not take a sample yourself.

@wleftwich do you see a problem with deprecating the `data_sample` argument?

**Comment by wleftwich** [comment]
> do you see a problem with deprecating the data_sample argument?

No, that seems reasonable.

**Comment by fgregg** [comment]
oh, I see, never mind

**Comment by fgregg** [comment]
Closed by #477
