### ISSUE TITLE
EOF error in python 2.7 (not in python 3.5)

### ISSUE THREAD

**Issue by titipata** [datamade/dedupe#478]
I got an error when running `consoleLabel` on Jupyter notebook (my Jupyter version is `4.1.0`) using Python 2.7 as follows.

```python
dedupe.consoleLabel(deduper)
```

Here is an error:

```
EOFError                                  Traceback (most recent call last)
<ipython-input-41-5f16b23568e5> in <module>()
----> 1 dedupe.consoleLabel(deduper)

~/anaconda2/lib/python2.7/site-packages/dedupe/convenience.pyc in consoleLabel(deduper)
     55             while not valid_response:
     56                 print('(y)es / (n)o / (u)nsure / (f)inished', file=sys.stderr)
---> 57                 label = input()
     58                 if label in ['y', 'n', 'u', 'f']:
     59                     valid_response = True

EOFError: EOF when reading a line
```

I'm wondering if there is an error for others who use Python 2.7 also. Or, the error is raised because of Jupyter notebook. I see no error when using Python 3.5.

**Comment by fgregg** [comment]
This seems like a Jupyter problem.

**Comment by titipata** [comment]
I think so too. We can close the issue if it's not related. I'm just wondering if there are other people who has the same problem running dedupe on Jupyter notebook.

**Comment by nateyoder** [comment]
I'm getting this issue as well. Did you ever find a work around @titipata ?  Thanks!

**Comment by titipata** [comment]
Hello @nateyoder! it has been quite a while on this issue. I don't remember how I solved an issue actually.  I'm not sure if changing [convenience.py#L56](https://github.com/datamade/dedupe/blob/372716493b99fc7f89f9e142c0c5a694420a0484/dedupe/convenience.py#L56) from `input` to `raw_input` will help solve the problem or not. In this case, you might have to download `dedupe`, fix L56, and use `setup.py` in order to install the library.

**Comment by nateyoder** [comment]
All good.  I ended up getting it to work by basically doing exactly what you suggested by replacing [line 4](https://github.com/datamade/dedupe/blob/372716493b99fc7f89f9e142c0c5a694420a0484/dedupe/convenience.py#L4) with:

```python
try:
    input = raw_input
except NameError:
    pass
```

Thanks!
