### ISSUE TITLE
Python MemoryError while working with large datasets

### ISSUE THREAD

**Issue by LokeshRishi** [datamade/dedupe#480]
Python gives MemoryError while trying to do _clustering_ on a server with 256 GBs of RAM, is there is a way to cut down the computation cost?

The two datasets are:
1. 180,000 rows, 3 columns
2. 5,000,000 rows, 3 columns

I really appreciate any help you can provide.

**Comment by fgregg** [comment]
yes, use a database like in
http://datamade.github.io/dedupe-examples/docs/mysql_example.html

**Comment by LokeshRishi** [comment]
Thanks for the reply, @fgregg. I am working on Entity Resolution, could you help me on using mysql database with that?

**Comment by fgregg** [comment]
I'm sorry, I don't understand what you are asking.

**Comment by LokeshRishi** [comment]
I am getting the following error while trying to run _mysql example_:

> downloading Illinois-campaign-contributions.txt.zip (~60mb) ...
> extracting Illinois-campaign-contributions.txt.zip
> importing raw data from csv...
> creating donors table...
> creating indexes on donors table
> creating recipients table...
> creating contributions table
> Traceback (most recent call last):

>   File "mysql_db_init.py", line 141, in <module>
>     c.execute("INSERT INTO contributions "

>   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
>     self.errorhandler(self, exc, value)

>   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorvalue

> _mysql_exceptions.OperationalError: (1411, "Incorrect datetime value: ' ' for function str_to_date")
>

**Comment by fgregg** [comment]
Please report issues about dedupe-examples in the the dedupe-examples repo. https://github.com/datamade/dedupe-examples

**Comment by LokeshRishi** [comment]
Done, thanks!
