### ISSUE TITLE
datamodel.py [ZeroDivisionError: float division]

### ISSUE THREAD

**Issue by kyleobrien91** [datamade/dedupe#481]
I came across an issue when executing `deduper.readTraining` on some old training data. 

After much debugging in the `datamodel.py` file, I noticed the following:
When comparing two records with a predicate with missing data (in my case 'address'), this errors out with `ZeroDivisionError: float division`

My trace stack looks like:
```bash
Traceback (most recent call last):
  File "deduper_new.py", line 644, in <module>
    load_training_from_gc_storage(dedupe)
  File "deduper_new.py", line 570, in load_training_from_gc_storage
    deduper.readTraining(f)
  File "/home/kyle/.virtualenvs/hidden/local/lib/python2.7/site-packages/dedupe/api.py", line 694, in readTraining
    self._addTrainingData(training_pairs)
  File "/home/kyle/.virtualenvs/hidden/local/lib/python2.7/site-packages/dedupe/api.py", line 888, in _addTrainingData
    new_data['distances'] = self.data_model.distances(examples)
  File "/home/kyle/.virtualenvs/hidden/local/lib/python2.7/site-packages/dedupe/datamodel.py", line 90, in distances
    record_2[field])
  File "affinegap/affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1788)
  File "affinegap/affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1615)
ZeroDivisionError: float division
```

Some debugging around line 82 of the datamodel.py file reveals the following:
- record_1 == `{u'phone_number': u'', u'name': u'Random Person One', u'source': u'spree', u'key': u'c63630', u'address': u'', u'email_address': u'hidden'}`
- record_2 == `{u'phone_number': u'', u'name': u'Random Person Two', u'source': u'spree', u'key': u'c151515', u'address': u'', u'email_address': u'hidden'}`
- `field` is ` 'address'`
- `record_1[field]` is `u''`
- `record_2[field]` is `u''`

I can't be sure that the empty values for `record_1[field]` and `record_2[field]` contribute to the zero division error (I haven't ventured into the `compare` function). However, my question is, wouldn't the check on line 81 be better as follows or am I not understanding something?
```python
if record_1[field] and record_2[field]:
```
instead of current version:
```python
if record_1[field] is not None and record_2[field] is not None :
```

**Comment by fgregg** [comment]
Sorry for the headache. This has to do with how dedupe now handles missing data. It used to be that each variable and so each comparator defined what indicated a missing value. For strings it was an empty string `''`, for long lat it was the tuple `(0,0)`, etc. Now, for every variable type, `None` is missing value.

This is definitely the way we want to handle this. In your training data json file replace empty strings with `null`/

**Comment by jilljenn** [comment]
We all wish this error code could be different!

**Comment by fgregg** [comment]
@jilljenn please open an issue, or better yet a PR on https://github.com/datamade/affinegap
