### ISSUE TITLE
Saving model settings when custom comparators are used

### ISSUE THREAD

**Issue by QCaudron** [datamade/dedupe#486]
I've written some code to follow the basic CSV example :
http://datamade.github.io/dedupe-examples/docs/csv_example.html

I'm able to train a model, write the settings to file and, from within the *same* REPL, create a new `StaticDedupe` object using the written settings file. However, from another REPL, this fails with `SettingsFileLoadingException: This settings file is not compatible with the current version of dedupe. This can happen if you have recently upgraded dedupe.`

The REPL uses the exact same environment, nothing changes. It looks like the issue is with custom comparators. If I remove the fields where I define my own comparator functions, this issue goes away.

Is there a way to save a trained model that contains custom comparators ? Thanks !

**Comment by QCaudron** [comment]
Edit : Looks like if I define the comparator functions in the new REPL before I try to read the settings into a new `StaticDedupe`, the model settings loads just fine.

**Comment by fgregg** [comment]
Looks like you figured it out!
