### ISSUE TITLE
Is there anyway to reduce the memory usage when dedupe data?

### ISSUE THREAD

**Issue by eminarcissus** [datamade/dedupe#492]
I'm quite new to this lib and I did some test last week and find it works quite fantastic on finding the links between two independent datasets.

So I'm about to do a RecordLink from a dataset A about 800,000 size to dataset B about 5,900,000  size. The fields including are name/address/district. The running machine is OSX macbook pro with 16gigs memory and I did follow the instruction to re-compile numpy with openblas and re-install the dedupe to take in advantage of the multiprocess ability.

From the mysql example it using Dedupe class as example.
Because I'm not quite comfortable working with SQL in data so I'm trying to port the code using mongo in-together with pandas for such case.

Running until right here
for field in deduper.blocker.index_fields :
    c2.execute("SELECT DISTINCT {field} FROM processed_donors "
               "WHERE {field} IS NOT NULL".format(field = field))
    field_data = (row[0] for row in c2)
    deduper.blocker.index(field_data, field)

This part will extract all unique values from a field and index this field by all values. So take my case into account I will need to extract all 800k + 5900k address into the memory and do TFIDF indexing for the field of 'address' I think that's not quite applicable even if I do switch to a dedicated machine to do the work, so I don't know if it is possible to make the indexing process working as a generator to reduce the memory it requires to handle such tasks.

Don't know if my understanding is correct, any helps will be real appreciate, also thanks very much for creating such a powerful lib :)

**Comment by fgregg** [comment]
In the mysql example we use [server side cursors](http://techualization.blogspot.com/2011/12/retrieving-million-of-rows-from-mysql.html) that act a lot like a generator to deal with the exact issue you mention. I don't know if mongo-db offers any similar facilities.

BTW, when you are doing record linkage you only need to index the second table.
