### ISSUE TITLE
core.randomPairsMatch() explodes in some cases

### ISSUE THREAD

**Issue by gwerbin** [datamade/dedupe#494]
The function [`core.randomPairsMatch()`](https://github.com/datamade/dedupe/blob/master/dedupe/core.py#L47-L62) gives nonsensical/explosive results in certain cases because it casts negative floats to unsigned integers.

In particular, at [line 58-59](https://github.com/datamade/dedupe/blob/master/dedupe/core.py#L58), the result of 
```python
n_records_b * numpy.floor(random_pairs/n_records_B)
```
occasionally contains a value that is _greater_ than its corresponding value in `random_pairs`. The effect of this is that when we compute
```python
random_pairs - n_records_B * i
```
we can end up with a negative element, which is then cast into an enormous unsigned integer and thereby an incorrect result. This causes `RecordLink.sample()` to fail gracelessly with a `KeyError`.

I understand floating-point operations can be implementation-dependent. I am able to reproduce the issue on OS X El Capitan with the following:

```python
import random
import numpy
from heapq import nlargest

random.seed(43770)

n_records_A = 41198
n_records_B = 52151
sample_size = 5000

n = int(n_records_A * n_records_B)
random_pairs = numpy.array(random.sample(range(n), sample_size), dtype = 'f')

i = numpy.floor(random_pairs / n_records_B)
j = random_pairs - n_records_B * i

for orig, floored, j_elem in zip(random_pairs, n_records_B * i, j):
    if orig < floored:
        print("j contains a negative number! {} - {} = {}".format(orig, floored, j_elem))

print("Top 5 values in j after casting to uint: {}".format(nlargest(5, j.astype('uint'))))
```

So the problem seems to be floating-point strangeness in `random_pairs / n_records_B`.

If I understand what this function is trying to do, you could implement it more safely and cleanly as:
```python
def randomPairsMatch2(n_records_A, n_records_B, sample_size):
    n = int(n_records_A * n_records_B)
    random_pairs = random.sample(range(n), sample_size)  # no need to cast to array for this
    i, j = np.unravel_index(random_pairs, (n_records_A, n_records_B))
    return zip(i, j)
```

**Comment by fgregg** [comment]
I didn't know about unravel_index! That seems useful. Let me do some testing.
