### ISSUE TITLE
Matching financial transactions?

### ISSUE THREAD

**Issue by js1972** [datamade/dedupe#498]
Hi, Just come across your repo here and am wondering if matching financial transactions would be a good fit it..?
I'm look for ways to parse finance transactions for matches where - for example - an invoice exists and there are many payments against this invoice but no key field to tie them together. They could have matching texts, vendor name or something but its largely unknown.

I'm thinking I could use dedupe to find matches, then go through each matched group of transactions and sum the dollars - if its zero we can clear those transactions... and so on...

So just wondering if you think dedupe could be used in this scenario?

**Comment by fgregg** [comment]
Give it a shot.
