### ISSUE TITLE
say more on testing against canonical dataset in README

### ISSUE THREAD

**Issue by hancush** [datamade/dedupe#502]
why would a user [want to do this](https://github.com/datamade/dedupe#test-using-canonical-dataset-from-bilenkos-research)? is it as simple as "don't believe us? run this"? 

say a bit more about why we include this in the README.

**Comment by fgregg** [comment]
This is basically an integration test https://en.wikipedia.org/wiki/Integration_testing

**Comment by fgregg** [comment]
Does this make sense @hancush ?

**Comment by hancush** [comment]
i was trying to get at why this section is relevant to a user rather than a developer.

this readme seems oriented toward people who want to develop dedupe while dedupe-examples is more useful for people trying to use dedupe. on second thought, i don't think testing necessarily needs to be expounded upon if we divert the people who only want to use dedupe to dedupe-examples before they get here, as discussed in #503.

**Comment by fgregg** [comment]
okay, closing for now.
