### ISSUE TITLE
add link to api docs/examples under 'using dedupe' in README

### ISSUE THREAD

**Issue by hancush** [datamade/dedupe#503]
we [get people thru the installation](https://github.com/datamade/dedupe#using-dedupe) then leave them hanging. let's add something like 'familiarize yourself with dedupe's api and our examples suite, then get started on your project' with links to the [api docs](https://dedupe.readthedocs.io/en/latest/API-documentation.html) + [examples repo](https://github.com/datamade/dedupe-examples) (which are super helpful and quite extensive but a little buried in this readme). 

i know they're listed in the important links section but having them here makes our startup instructions more linear and thereby easier to follow.

**Comment by fgregg** [comment]
sounds good to me.

**Comment by fgregg** [comment]
@hancush are you still interested in doing this?

**Comment by hancush** [comment]
oops, yep, see #508
