### ISSUE TITLE
Question regarding matchBlocks example

### ISSUE THREAD

**Issue by piggybox** [datamade/dedupe#515]
I'm confused about the example shown in the doc for `matchBlocks`. What's exactly the number in the list of set? How many lists should be in the set? Why does the 2nd line in the 2nd block (for Sam) use an empty list set? 

```
blocks =((
          [(1, {'name' : 'Pat', 'address' : '123 Main'}, set([]))],
          [(3, {'name' : 'Pat', 'address' : '123 Main'}, set([]))]
          ),
         (
          [(1, {'name' : 'Pat', 'address' : '123 Main'}, set([1])),
           (2, {'name' : 'Sam', 'address' : '123 Main'}, set([]))],
          [(3, {'name' : 'Pat', 'address' : '123 Main'}, set([1]))]

          )
         )
linker.matchBlocks(blocks) 
```

Thanks

**Comment by fgregg** [comment]
Could you explain what part of this documentation is inadequate or confusing https://dedupe.readthedocs.io/en/latest/API-documentation.html#Dedupe.matchBlocks

**Comment by piggybox** [comment]
I understand this additional set provides the block coverage information. In the example shown in the document as two `Pat` records have already been compared in the first block, so they are marked as `set([1])` in the 2nd block. 

However, how to construct that `set()` is still not clear to me. Does that `1` refer to the first block or just a 1/0 flag? If that number is refereed to the index of block, when the records have already been compared in multiple previous blocks, should I use something like `set([1, 2, 3])`?

**Comment by fgregg** [comment]
> Does that 1 refer to the first block or just a 1/0 flag?

It refers to the first block

> If that number is refereed to the index of block, when the records have already been compared in multiple previous blocks, should I use something like set([1, 2, 3])?

Yes.

A pull request that made this documentation clearer would be very welcome.

**Comment by fgregg** [comment]
Has your question been answered?

**Comment by piggybox** [comment]
Yes，thanks！
