### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by AMongeEntytle** [datamade/dedupe#516]
When trying to apply dedupe to a small dataset, there is a chance to get an index out of bounds exception if the algorithm is not able to find any blocked pairs when computing the threshold. The error happens on api.py:79 when trying to compute the recall value in case expected_dupes is empty. 
To be fair, I am feeding dedupe with a test dataset (30 records, all already deduped) but I guess it could be nice not to output an "Index out of bounds" exception, but state something like "No blocks could be computed.".

**Comment by fgregg** [comment]
Hi @AMongeEntytle, this should have gotten fixed in the last release. Can you try upgrading?

**Comment by AMongeEntytle** [comment]
Hi @fgregg, no I didn't sorry. I will update and come back with the status.

**Comment by AMongeEntytle** [comment]
Fixed in 1.6.1 (Error now is much more verbose). Thank you @fgregg !!
