### ISSUE TITLE
Is there a way to do pairwise comparison?

### ISSUE THREAD

**Issue by pudo** [datamade/dedupe#520]
Having trained an instance of ``Deduper`` and after using it to cluster a larger dataset, it would be very useful to be able to do pairwise comparisons of two records and retrieve a similarity score based on  dedupe's predicates. This would be used for ranking in a user interface.

I've tried to do this by manually calling ``matchBlocks()`` with a single manually constructed, two-entry block, but that does not seem to work (giving me ``(1.0, 1.0)`` for any two records).

While I'm almost sure what I am asking proves I don't understand the mathematics involved in dedupe, it seems better to ask than not.

**Comment by fgregg** [comment]
ranking of what?

making a custom two-entry block should work.

**Comment by pudo** [comment]
Thanks. I'll give it another shot. Re: Ranking -- in pudo/aleph, for example, I'm [fetching similar records from a database using ElasticSearch](https://data.occrp.org/entities/bed51c9919b910b76c56d7726d5aafe3ba1c4f4d), but would like to complement the ES scoring by running dedupe's scoring on the result set. My sense is that it would score down many of the weird matches ES throws up.

**Comment by fgregg** [comment]
The gazetteer class could be used for directly fetching records.

**Comment by fgregg** [comment]
How's this going @pudo?

**Comment by pudo** [comment]
Yes. The previous issue was actually a mistake in training, not with regards to the pairwise comparison itself. It works quite well now.
