### ISSUE TITLE
Some problems with dedupe-example's extended-variables

### ISSUE THREAD

**Issue by miscy210** [datamade/dedupe#525]
Recently, I was trying to study the "dedupe" module and downloaded the "dedupe-example" package so to learn the work flow. Sooner I got stuck with the extended-variables example when trying to construct the data sample of dedupe with the code 
        deduper.sample(data_d,1500).
With the analysis of the console error report and some debug, I found that when to construct the random sample keys with function
        dedupe.labeler.ActiveLearner.sample_combo
which used basic function
        core.randomPairs(len(data),random_sample_size).
The result called "KeyError: ****" (here **** means some large number) Which exactly called by "Numerical overflow".
Then I cut the input parameter len(data) to one third (len(data)//3), It went well.
By analyzing the basic function core.randomPairs, I wonder why the construction of random pairs went this way 
      def randomPairs(n_records, sample_size):
          """
              Return random combinations of indices for a square matrix of size
               n records
          """
          n = int(n_records * (n_records - 1) / 2)

          if sample_size >= n :
              random_pairs = numpy.arange(n)
          else:
              random_pairs = numpy.array(random.sample(range(n), sample_size))
    
          b = 1 - 2 * n_records

          i = numpy.floor((-b - numpy.sqrt(b ** 2 - 8 * random_pairs)) / 2).astype('uint')
          j = numpy.rint(random_pairs + i * (b + i + 2) / 2 + 1).astype('uint')

          return zip(i, j)

Who can give a favor and help me understand this construction principle?

**Comment by fgregg** [comment]
This has already been fixed on master. If you'd like to check I'd appreciate it.

Here's a discussion of what's going with that function
http://stackoverflow.com/a/14839010/98080

**Comment by miscy210** [comment]
@fgregg Thanks a lot.
